# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/ffirstsome
    docker:
      - image: circleci/ruby:3.0.3-browsers
        environment:
          RAILS_ENV: test

    steps:
      - checkout

      # Bundle install dependencies
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install --path vendor/bundle --without production development

      # run RSpec
      - run: bundle exec rspec spec/

