name: "Github CI"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0.3']

    env:
      RAILS_ENV: test

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - run: gem install bundler

      - run: bundle install --path vendor/bundle

      - name: workflow:generate_start
        run: bundle exec rake workflow:generate_github_start workflow_id=$GITHUB_RUN_ID workflow_run_number=$GITHUB_RUN_NUMBER branch=${{ github.head_ref || github.ref_name }}

      - name: Run rspec tests
        run: bundle exec rspec spec/service

      - name: workflow:generate_end
        run: bundle exec rake workflow:generate_github_end workflow_id=$GITHUB_RUN_ID workflow_run_number=$GITHUB_RUN_NUMBER branch=${{ github.head_ref || github.ref_name }}